name: mira
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/icons8-lista-vazia-50.png

  fonts:
     - family: EduAUVICWANTArrows
       fonts:
         - asset: assets/fonts/EduAUVICWANTArrows-Bold.ttf
         - asset: assets/fonts/EduAUVICWANTArrows-Medium.ttf
         - asset: assets/fonts/EduAUVICWANTArrows-Regular.ttf
         - asset: assets/fonts/EduAUVICWANTArrows-Semibold.ttf
     - family: Nunito
       fonts:
         - asset: assets/fonts/Nunito-Black.ttf
         - asset: assets/fonts/Nunito-BlackItalic.ttf
         - asset: assets/fonts/Nunito-Bold.ttf
         - asset: assets/fonts/Nunito-BoldItalic.ttf
         - asset: assets/fonts/Nunito-ExtraBold.ttf
         - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
         - asset: assets/fonts/Nunito-ExtraLight.ttf
           weight: 400
